Remove invalid option combination
Adding an interface address to a chassis cannot work because chassis does not implement Plenaries.  Ie, this always fails:

    aq add_interface_address --chassis chassis.fqdn.ms.com --interface mgmt --ip x.y.z.w
    ...
    Internal Server Error: Class Chassis does not have a plenary handler

The same is true of adding an interface address to a console_server.

Addresses-Issue: AQUILONAQD-1761